upstream:
  default:
    - 1.1.1.1
    # vodafone
    - 203.109.191.1
    - 203.118.191.1
    # adguard
    - 94.140.14.140
    - 94.140.14.141
customDNS:
  mapping:
    # *.haume.nz resolves to 172.16.1.50
    gw.haume.nz: 172.16.1.1
    kauri.haume.nz: 172.16.1.50
    books.haume.nz: 172.16.1.50
    cloud.haume.nz: 172.16.1.50
    diatum.haume.nz: 172.16.1.50
    git.haume.nz: 172.16.1.50
    media.haume.nz: 172.16.1.50
    music.haume.nz: 172.16.1.50
    static.haume.nz: 172.16.1.50
    status.haume.nz: 172.16.1.50
    statping.haume.nz: 172.16.1.50
conditional:
  rewrite:
    # rewrite foo.spack.org as foo.haume.nz before dns resolution
    spack.org: haume.nz
    # rewrite firefox canary to something non-existant 
    # https://support.mozilla.org/en-US/kb/canary-domain-use-application-dnsnet
    use-application-dns.net.: diedie.die
#  mapping:
    # queries for *.groundtruth.co.nz are directed to a specific resolver
#    groundtruth.co.nz: 192.168.81.1
blocking:
  blackLists:
    ads:
      # https://github.com/topics/pihole-blocklists
      - https://dblw.oisd.nl/
      - https://raw.githubusercontent.com/hectorm/hmirror/master/data/adguard-simplified/list.txt
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
#      - |
#        spack.org
  whiteLists:
    ads:
      - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
      #- https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/white_list.txt
#      - |
#        shand.net
#        spack.org
#        shmoo.com
#        pekapekahill.nz
#        livingground.nz
#        groundtruth.co.nz
#        trap.nz
#        haume.nz
  clientGroupsBlock:
    default:
      - ads
port: 53
httpPort: 4000
